Jenkinsfile_CNP, build.gradle, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> Supression added and fixed checkstyle issues

src/main/resources/wa-task-cancellation-CIVIL-CIVIL.dmn, src/main/resources/wa-task-completion-CIVIL-CIVIL.dmn, src/main/resources/wa-task-configuration-CIVIL-CIVIL.dmn, src/main/resources/wa-task-initiation-CIVIL-CIVIL.dmn, src/main/resources/wa-task-permissions-CIVIL-CIVIL.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/DmnDecisionTable.java
=> Changed names for DMN's based on jurisdiction and casetypeid.

src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
=> FIX : Court management location and region added in configuration

config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/DmnDecisionTable.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
=> Changed file names and test cases

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> Changed post event name

src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> Changed DMN permissions and unit test cases

config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-CIVIL-GENERALAPPLICATION.dmn, src/main/resources/wa-task-completion-CIVIL-GENERALAPPLICATION.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskCompletion.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/CIV-1873
Refactor WA GA Task Completion and Cancellation w.r.t Confluence page
https://tools.hmcts.net/confluence/display/CRef/Civil+Work+Allocation+Configuration?focusedCommentId=1600062598#CivilWorkAllocationConfiguration-6.5.5Taskcancellation
```
[ ] Yes
[ ] No
```
=> CIV-1873 Refactor WA GA Task Completion and Cancellation

src/main/resources/wa-task-configuration-civil-civil.dmn
=> Changed next step url

src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> Fixed Authorisations for judges and test cases

src/main/resources/wa-task-initiation-CIVIL-GENERALAPPLICATION.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-3461
WA Task Initiation: Task Name should be lowercase and not as the event ID
Example Task name after the change
1. Review Application for summary judgement
2. Application for multiple types - revisited make order for written representations
3. summary judgement - revisited make order for written representations
```
[ ] Yes
[ ] No
```
=> CIV-3461 Task Name should be lowercase

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> view and respond init & comp dmn

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
=> removed extra location field from DMN

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
=> Fixed duplicate work type

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
=> added properties along the specific access changes

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
No JIRA link 
Fixed specified access URL next step
```
[ ] Yes
[X ] No
```
=> Fixed specified access URL next step

src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
=> Fixed issues for specific access

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
Fixed issues for specific access for next step
```
[ ] Yes
[ ] No
```
=> Fixed issues for specific access for next step

Jenkinsfile_CNP, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-4973
1. Set location name and region
2. Change the field isCcmccLocation to true or false
3. update the unit test
```
[ ] Yes
[ ] No
```
=> CIV-4973 Set location name and region

bin/add-roles.sh, config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java
ADMINISTRATOR -> ADMIN
LEGAL OPERATIONS -> LEGAL_OPERATIONS
https://tools.hmcts.net/jira/browse/CIV-5146
```
[x ] Yes
[ ] No
```
=> Updated DMNs to change the roleCategory name

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> Changed Event to NOTIFY_INTERIM_JUDGMENT_DEFENDANT from DEFAULT_JUDGMENT

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-5200
Adding changes for Spec Journey
```
[ ] Yes
[ x] No
```
=> Adding changes for Spec Journey

Jenkinsfile_CNP, bin/import-dmn-diagram.sh, config/owasp/suppressions.xml
- introduced another method to use for preview upload dmn preview
```
[ ] Yes
[ ] No
```
=> added relevant changes to start using tenant id and product

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-6196
Modified Task Initiation and Permissions DMN to make list for hearing cases visible for caseworkers at ccmcc (Before SDO scenario)
Added related test cases
```
[x ] Yes
[ ] No
```
image](https://user-images.githubusercontent.com/107422736/203559891-5ca38d8d-7e60-4fba-82c2-a76dd500aec9.png)
=> CIV-6196 Added before sdo scenario for List for Hearing cases

build.gradle, charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.preview.template.yaml, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-5176
Refactor GA Task Initiate dmns to ignore nested if condition
Screenshot are attached in the ticket comments section
```
[ ] Yes
[ ] No
```
=> CIV-5176DMNs for GA Creation Urgent Appln.

charts/civil-task-configuration/values.preview.template.yaml
CIV-6106
Removed user-profile-importer
Changed user-profile API to use AAT instance.
Increase ccd-data-store cpu
Disable camunda cron 
```
[ ] Yes
[ x ] No
```
=> CIV-6106 - Remove Dependencies on User Profile

charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-6089
Move postgresql implementation for WA to chart-java instead of pulling from external always. Should reduce failure probability and also maintenance.
```
[ ] Yes
[ ] No
```
=> CIV-6089 Move postgresql to chat-java

.gitignore, Jenkinsfile_CNP, charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.preview.template.yaml, charts/civil-task-configuration/values.yaml
CIV-6105
- add disabled key vaults instead of empty
- remove duplicate URLs
- remove duplicate functions
- remove redundent postgresql use
```
[ ] Yes
[ x ] No
```
=> CIV-6105 jenkins and charts clean

config/owasp/suppressions.xml, src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> Adding row for 6110

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-6603
SDO submission for 3.5 dmns is not creating transfer case offline task but create schedule a hearing task
```
[ ] Yes
[x] No
```
=> Feat/civil 6603 3.5 dmns is not creating transfer case offline task

config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
Update to SDO DMN configuration
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-6700
Urgent requiremnt changes to SDO DMNs 
Task Initiation DMN
Task Configuration DMN
Task Permissions DMN
Task Cancellation DMN
Task Completion DMN
```
[ ] Yes
[x ] No
```
=> Civ 6700 Update to SDO DMN configuration

infrastructure/variables.tf
CIV-5707
remove unused variable
```
[ ] Yes
[ x ] No
```
=> CIV-5707 - remove unused variable

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
Reverts hmcts/civil-wa-task-configuration#76
=> Revert "added dmn config changes for caseprogression"

config/owasp/suppressions.xml, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
Reverts hmcts/civil-wa-task-configuration#63
=> Revert "Feat/civil 4481 dmn permission"

Jenkinsfile_CNP, build.gradle, charts/civil-task-configuration/values.preview.template.yaml, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java
=> CIV-4481 Update dependency check version

charts/civil-task-configuration/Chart.yaml, src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
Reverts hmcts/civil-wa-task-configuration#107
=> CIV-6547 - Revert master -changed link for ScheduleAHearing task

.github/dependabot.yml, .github/workflows/stale.yml, charts/civil-task-configuration/Chart.yaml
CIV-5433
Correct Stale Workflow
```
[ ] Yes
[ x ] No
```
=> CIV-5433 - Correct Stale Workflow

.dependabot/config.yml, .github/renovate.json, Dockerfile
https://tools.hmcts.net/jira/browse/CIV-7082
Dependabot removed and its tasks delegated to renovate
```
[ ] Yes
[x] No
```
=> CIV-7082 remove dependabot and delegate its tasks to renovate

.github/CODEOWNERS
CIV-5433
Correct Code Owners
```
[ ] Yes
[ x ] No
```
=> CIV-5433 - Correct Code Owners

build.gradle, charts/civil-task-configuration/Chart.yaml
=> CIV-0000 Genapp frozen lock removal and chart upgrade

bin/add-roles.sh, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-6861
Add Unless order WA Task
```
[ ] Yes
[ ] No
```
=> CIV-6861 Add Unless Order Scheduler Task

charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.preview.template.yaml, charts/civil-task-configuration/values.yaml, config/owasp/suppressions.xml
Adding `SERVICE_REQUEST_UPDATE` and `SERVICE_REQUEST_UPDATE_CLAIM_ISSUED` to relevant chart values files to resolve PBAv3 issue
```
[ ] Yes
[x] No
```
=> CIV-0000 added service request values to values.preview

config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-20860 as there is no fix available yet.
```
[ ] Yes
[x] No
```
=> CIV-TASK Temporarily suppress CVE-2023-20860

.git-config/hooks/commit-msg, .git-config/hooks/pre-commit, .github/workflows/main.yml, README.md
https://tools.hmcts.net/jira/browse/CIV-7230
Enforce conventions on branch names and commit messages
```
[ ] Yes
[x] No
```
=> CIV-7230 Enforce conventions on branch names and commit messages

Dockerfile
N/A
Updating the JDK distro to fix build after some PlatOps changes.
```
[ ] Yes
[x] No
```
=> CIV-TASK Change JDK distro

src/main/resources/wa-task-types-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaWaTaskTypesTest.java
=> CIV-6942 changing the dmn name and specific access request names

bin/utils/process-definition.sh
CIV-0000 - Downgrade def processor version
```
[ ] Yes
[ ] No
```
=> CIV-0000 - Downgrade def processor version

bin/utils/process-definition.sh
CIV-0000 -  def processor version to latest
```
[ ] Yes
[ ] No
```
=> CIV-0000 -  def processor version to latest

src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-8009
Increase SLA to 20 Days for all Work Allocation Tasks for non urgent application
```
[ ] Yes
[ ] No
```
=> CIV-8009 Increase SLA to 20 Days for Non Urgent appln

build.gradle, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-4923
Removed columns "Working Day Allowed", "Delay duration" and added new column "Delay until" in initiation DMns
Added new variable in configuration DMNs.
```
[ ] Yes
[ ] No
```
=> CIV-4923 Added configuration for bank holiday

bin/add-roles.sh
Adding wa access profile
```
[ ] Yes
[ ] No
```
=> CIV-0000 Adding wa access profile

Jenkinsfile_CNP, bin/variables/load-preview-environment-variables.sh, charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.preview.template.yaml
CIV-0000 Updating urls to .preview.platform.hmcts.net
```
[ ] Yes
[x ] No
```
=> CIV-0000 Updating urls to .preview.platform.hmcts.net

src/main/resources/wa-task-types-civil-civil.dmn
=> CIV-000 remove CP related tasks

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-7497
Added new condition and rule for CUI SDO support. Attaching snap shot and underline the new row and column.
https://user-images.githubusercontent.com/115545612/236014734-31d06009-dcbf-496d-b970-547d1990fcb5.png
https://user-images.githubusercontent.com/115545612/236014999-e3a2937f-c3cd-4a6b-8368-0e2419a78b1f.png
```
[ ] Yes
[x] No
```
=> CIV-7497 Adding SDO changes for CUI.

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-7930
Added new conditions for consent order After SDO
```
[ ] Yes
[ ] No
```
=> CIV-7930 Consent Order Refer to judge

Jenkinsfile_CNP, config/owasp/suppressions.xml, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn
https://tools.hmcts.net/jira/browse/CIV-7865
This PR has changes to update existing CIVIL TASK INITIATION DMN  to allow for Part Admit journeys in Legal Rep intention to Proceed for SDO
task triggered on camunda 
task logged on xui 
```
[ ] Yes
[x] No
```
=> CIV-7865 - SDO DMN for Part Admit Journeys

src/main/resources/wa-task-completion-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskCompletion.java
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-8609
Added autocompletion for APPROVE_CONSENT_ORDER event trigger
```
[ ] Yes
[ x] No
```
=> CIV-8609 Added autocompletion for APPROVE_CONSENT_ORDER event trigger

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-8884
added 2 new roles.
```
[ ] Yes
[x] No
```
=> CIV-8884 - CUI: create and link access roles

charts/civil-task-configuration/values.preview.template.yaml, src/main/resources/wa-task-initiation-civil-generalapplication.dmn
https://tools.hmcts.net/jira/browse/CIV-8931
"Adjourn or vacate a hearing" is updated to "Adjourn a hearing"
```
[ ] Yes
[ ] No
```
=> CIV-8430 Refactor GA type Adjourn hearing

config/owasp/suppressions.xml
=> CIV-0000 Update suppressions.xml

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CIV-9513
```
[ ] Yes
[ ] No
```
=> CIV-9513 removed cui exclusion

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-9440
added 'MEDIATION_UNSUCCESSFUL' event in Init DMN
```
[ ] Yes
[x] No
```
=> CIV-9440 - Added Mediation Unsuccessful event in init dmn.

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-7897
added new profile
```
[ ] Yes
[x] No
```
=> CIV-7897 - Update add-roles.sh

build.gradle
Upgrading to latest java-logging version. Please carefully review the release notes for this latest version, as there are some removals to consider that may affect your application.
=> CIV-0000 Java Logging Upgrade

build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgrading to java 17
```
[ ] Yes
[ ] No
```
=> CIV-0000 Upgrading to java 17

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-5339
added new profile
```
[ ] Yes
[x] No
```
=> CIV-5339 - Release 2 - LIP v LIP Update Access Profile JSON

build.gradle, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-9930
- New colum for vary judgement added with this logical expression "if(list contains(additionalData.Data.generalAppType.types, "VARY_JUDGEMENT")) then true else false".
- Added new rown for vary judgements. 
```
[ ] Yes
[ ] No
```
=> CIV-9930 vary Judgement

Jenkinsfile_CNP
CIV-0000 remove enable helm
```
[ ] Yes
[ ] No
```
=> CIV-0000 remove enable helm

.github/workflows/main.yml, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-10231
Update GA type settle by consent
```
[ ] Yes
[ ] No
```
=> CIV-10231 Update GA type settle by consent

bin/add-roles.sh
=> CIV-0000 Add pcq extractor role

build.gradle
CIV-0000 fix CVE
```
[ ] Yes
[ ] No
```
=> CIV-0000 fix CVE

build.gradle, src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-6614
Feature toggle for WA dmns differentiation for every release and feature should be implemented in civil
```
[ ] Yes
[x] No
```
=> CIV-0000 Combined-3.5-and-4

Jenkinsfile_CNP, build.gradle, charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.preview.template.yaml, charts/civil-task-configuration/values.yaml, config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-10567
https://tools.hmcts.net/jira/browse/CIV-10978
WA Task: create 'Request for transfer online case' task name
(Re)Create SDO task when judge decided not to draw order and transfer the case
```
[ ] Yes
[X ] No
```
=> CIV-10567 CIV-10978 Task for NotSuitableSDO events

Jenkinsfile_nightly
Nightly passed in https://build.hmcts.net/view/Civil/job/HMCTS_a_to_c_Nightly/job/civil-wa-task-configuration/job/nightly-dev/
=> CIV-0000 fix secrets in nightly --  Jenkinsfile_nightly

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/CIV-10922
WA Task: Transfer existing Civil task of the case
```
[ ] Yes
[X ] No
```
=> CIV-10922 TOC reconfigure tasks

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> CIV-0000 CP and EA With Prod feature toggle

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn
=> CIV-0000 fix completion task

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> CIV-0000 CUI Task DMN's to be merged with master with CUI feature toggle

src/main/resources/wa-task-completion-civil-civil.dmn
=> CIV-0000 CUI Task DMN's

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
NA
added 3 missing rules
```
[ ] Yes
[x] No
```
=> CIV-0000 - Updated init DMN

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
=> CIV-11636  : CUI Task DMN's

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/CIV-11363
add new RETRIGGER_CASES event to ReConfigure
```
[ ] Yes
[X] No
```
=> CIV-11363 retrigger cases

src/main/resources/wa-task-completion-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/CIV-11501
Caseworkers unable to add case notes/take cases offline
```
[ ] Yes
[x] No
```
=> CIV-11501 Adding event for CASE_PROCEEDS_IN_CASEMAN

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java
=> CIV-0000 CUI  Prod DMN's

src/main/resources/wa-task-completion-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/CIV-11873
Added new entry in configuration DMNs to allow task completion without event
```
[ ] Yes
[ ] No
```
=> CIV-11873 update to make available event without task

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
- https://tools.hmcts.net/jira/browse/CIV-11394
- https://github.com/hmcts/civil-wa-task-configuration/pull/433
```
[ ] Yes
[x] No
```
=> CIV-11897 - WA Task

src/main/resources/wa-task-initiation-civil-civil.dmn
NA
Added process category Identifiers values for #107 and #108
```
[ ] Yes
[x] No
```
=> CIV-0000 - Added missing process category Identifiers values for #107 and #108

charts/civil-task-configuration/values.preview.template.yaml, config/owasp/suppressions.xml
=> CIV-0000 fix CVE Issue

config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-11732
```
[ ] Yes
[X] No
```
=> CIV-11732 Updated HMC WA Changes 

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-11617
Added rules to set court location for CTSC's tasks for checking claimant and defendant's flags
```
[ ] Yes
[X] No
```
=> CIV-11617 changed court for flags tasks

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn
TOC Release prep
```
[ ] Yes
[X ] No
```
=> CIV-0000 TOC Release

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
Bug Fix for TOC - OTHER options
```
[ ] Yes
[ X] No
```
=> CIV-0000 TOC Bug Fix

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-11540
Work Allocation in Claimant Response Journey
```
[ ] Yes
[x ] No
```
=> CIV-11540 Added work allocations task for CUI claimant welsh request

src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-11547
Added changes to trigger WA task for Claim Issue journey when Claim Issue Language = 'English + Welsh'
```
[ ] Yes
[x] No
```
=> CIV-11547 - Claim Issue: Issue Work Allocation 

src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-11311
Claimant Intention: Case Flags
```
[ ] Yes
[x] No
```
=> CIV-11311 Claimant Intention: Case Flags

src/main/resources/wa-task-configuration-civil-civil.dmn
CIV-0000 Adding "transferOnlineCase" for Admin role type
=> CIV-0000 Adding "transferOnlineCase" for Admin role type

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-11297
Generate a task when Help With Fees event saves reference number for hearing fee .
```
[ ] Yes
[x] No
```
=> CIV-11297 - Help With Fees hearing task

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> CIV-0000 Removing Toggle prod

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-12446
```
[ ] Yes
[ ] No
```
=> CIV-12446 added new rule for not suitable SDO

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-12486
Create Summary Judgement direction tasks
```
[ ] Yes
[X ] No
```
=> CIV-12486 Summary Judgement task

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-12331
Add to line 58 (roleCategory) and 60 (workType) true to columnt "Can Reconfigure"
```
[ ] Yes
[X] No
```
=> CIV-12331 role category CTSC set can reconfigure to true

charts/civil-task-configuration/Chart.yaml, charts/civil-task-configuration/values.yaml, config/owasp/suppressions.xml
=> CIV-10543 pointing_to_v15

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> CIV-12046 - added rule for CCJ

src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/CIV-12998
- Added UpdateDetailsInCasemanSystem to wa task types
```
[ ] Yes
[X] No
```
=> CIV-12998 Add UpdateDetailsInCasemanSystem wa task type

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/CIV-12796
=> CIV-12796 WA task not cancelled properly when case is taken offline

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> CIV-12936 Defence received in time - order that judgment is set aside

src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> CIV-12936 fix wording

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-13160
```
[ ] Yes
[ X] No
```
=> CIV-13160 Recreate SDO tasks on TOC Event

charts/civil-task-configuration/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSCCI-201
```
[ ] Yes
[ ] No
```
=> DTSCCI-201 upgrade helm chart

src/main/resources/wa-task-configuration-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java
https://tools.hmcts.net/jira/browse/CIV-13613
- Changed ScheduleAHearing to link to hearings tab in next steps rather than linking to add a case note
```
[ ] Yes
[X] No
```
=> CIV-13613 Schedule a hearing WA Task Update

src/main/resources/wa-task-configuration-civil-civil.dmn
DTSCCI-296
Remove duplicate role assignment for role reviewSpecificAccessRequestAdmin
```
[ ] Yes
[ ] No
```
=> DTSCCI-296 Remove duplicate role assignment

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn
https://tools.hmcts.net/jira/browse/CIV-13835
Removing WA3.5 flag from initiation, configuration and permissions dmn
```
[ ] Yes
[ X] No
```
=> CIV-13835 SDO R2 Release WA prod changes

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-14015
ClaimSettledRemoveHearing task
Initiation 
Condition 
Configuration
Permission
TaskTypes
Completion
Cancellation
```
[ ] Yes
[X ] No
```
=> CIV-14015 ClaimSettledRemoveHearing task

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-14117
Final order Welsh Translation task
**Permissions:**
**Configuration:**
**Initiation:**
Event name + toggle
Check for language (bottom row + added a new column)
task name
**Completion:**
```
[ ] Yes
[x] No
```
=> CIV-14117 - final order Welsh translation

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancelAllTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-14291
****
=> CIV-14291 WA Task Cancellation When Case Goes Offline

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/DmnDecisionTableBaseUnitTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancelAllTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
CIV-13347
Added test to check whether the event cancels all outstanding tasks, and rows so that Case proceeds in Caseman cancels all outstanding tasks
```
[ ] Yes
[X] No
```
=> CIV-13347 case proceeds in caseman cancels all tasks

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-14492
WA task not getting created to translate the claimant intention docs
```
[ ] Yes
[x ] No
```
=> CIV-14492 WA task not getting created to translate the claimant intention docs

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancelAllTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-14268
Case Discontinued Divergence - Take Case Offline
Initiation
Configuration
Task Types
Permissions
```
[ ] Yes
[ X] No
```
=> CIV-14268 Case Discontinued Divergence - Take Case Offline

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-14661
case flags for defendant lip
```
[ ] Yes
[N] No
```
=> CIV-14661 case flags for defendant lip

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-14270
Initiation DMN
Configuration DMN
Task Types
Completion
Permission
```
[ ] Yes
[ X] No
```
=> CIV-14270 Add task ClaimDiscontinuedRemoveHearing

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-14267
Work allocation: Validate discontinuance
```
[ ] Yes
[x] No
```
=> CIV-14367 add discontinue code to validate discontinuance event

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-14440
Initiation DMN
```
[ ] Yes
[ ] No
```
=> CIV-14440 Add task - Validate_Discontinuance_Claim_Claimant

src/main/resources/wa-task-completion-civil-generalapplication.dmn, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskCompletion.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-14334
In the 'Make an application' journey, the applicant has the chance to say whether they require assistance with their fees, and can select to apply for 'Help with Fees'. The system enables an Applicant LiP to provide the HwF reference number so that their application for help with their Application Fee can be assessed by a Caseworker.
**Does this PR introduce a breaking change?** (check one with …
=> CIV-14334 Submit function for HwF - GA for LiPs (Includes WA)

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> DTSCCI-292 - small claim direction task for judge not for la V3

src/main/resources/wa-task-cancellation-civil-generalapplication.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-completion-civil-generalapplication.dmn, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskCompletion.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-14130
Make caseworker events available for HwF additional application fee
```
[ ] Yes
[ x] No
```
=> CIV-14130 WA events for CaseWorker HWF

src/main/resources/wa-task-configuration-civil-civil.dmn
https://tools.hmcts.net/jira/browse/DTSCCI-679
```
[ ] Yes
[ ] No
```
=> DTSCCI-679 - Add manualDetermination task Type to config column for location CTSC

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-cancellation-civil-generalapplication.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-completion-civil-generalapplication.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn
https://tools.hmcts.net/jira/browse/DTSCCI-810
Update decision instance ttl to 90 days for all dmn
```
[ ] Yes
[ ] No
```
=> DTSCCI-810 - Update decision instance ttl to 90 days for all dmn

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-15022
Added a new Rule for LegalAdvisiorSDO
```
[ ] Yes
[ ] No
```
=> CIV-15022 - SDO task not being created for LA when claim was in mediation

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> CIV-14895 WA task to take case offline after set aside in error or defence received

src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
Untoggled mci permission config
```
[ ] Yes
[X] No
```
=> CIV-0000 MCI Release

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-14419
Direct task to judge/legal adviser if consent order and LiP involved
```
[ ] Yes
[x] No
```
=> CIV-14419 Direct task to judge/legal adviser if consent order and LiP involved

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-15062
Add roles for ctsc users
```
[ ] Yes
[x] No
```
=> CIV-15062 - add roles for ctsc

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-15204
Renaming of toggle, no functional changes
```
[ ] Yes
[x] No
```
=> CIV-15204 - rename feature toggle to batch 1

src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> CIV-0000 removed r2 toggle

src/main/resources/wa-task-configuration-civil-civil.dmn
=> CIV-0000 - updated role

Jenkinsfile_CNP, bin/pull-latest-civil-ccd-files.sh
=> DTSCCI-966 Update-ccd-import-files

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-15487 & https://tools.hmcts.net/jira/browse/CIV-15486
=> CIV-15486 15487 Manage Stay WA Configuration

src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java
NA
Updated task-types DMN with CUI task names.
```
[ ] Yes
[ ] No
```
=> CIV-0000 - Added CUI task names.

src/main/resources/wa-task-completion-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/CIV-15638
Remove task requirement for Fee Payment Outcome event
```
[ ] Yes
[x] No
```
=> CIV-15638 Remove task requirement for Fee Payment Outcome event

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
Preparing repo for Caseworker Events Batch 1 release
```
[ ] Yes
[ ] No
```
=> CIV-15617 - Preparing repo for CE B1 release

src/main/resources/wa-task-initiation-civil-civil.dmn
https://tools.hmcts.net/jira/browse/CIV-15624
Task name updated 
```
[ ] Yes
[ ] No
```
=> CIV-15624 - Incorrect WA task name for small track WA tasks

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-15282
Change Request for Reconsideration task so it checks whether a request has already taken place by other user.
```
[ ] Yes
[x] No
```
=> CIV-15282 - change task to run only once

bin/utils/process-definition.sh
=> DTSCCI-813 dynamic defs case type

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-15663
=> CIV-15663 Confirm Order Review Changes

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
=> CIV-0000 CUI CP Release - DO NOT MERGE UNTIL RELEASE

src/main/resources/wa-task-initiation-civil-civil.dmn
…PART_ADMISSION
https://tools.hmcts.net/jira/browse/DTSCCI-1152
DTSCCI-1152 Fix syntax of Respondent 1 Intention For Spec field for PART_ADMISSION
```
[ ] Yes
[ ] No
```
=> DTSCCI-1152 Fix syntax of Respondent 1 Intention For Spec field 

charts/civil-task-configuration/values.preview.template.yaml
=> CIV-15377 - Configure Role Assignments Url 

src/main/resources/wa-task-initiation-civil-civil.dmn
- Added new Has Lip and (Un)spec Allocated track columns
```
[ ] Yes
[X] No
```
=> CIV-0000 Initiation Columns

src/main/resources/privilege-calendar.json
DTSCCI-1298
update privilege-calendar.json to cater 27th dec 2024
```
[ ] Yes
[ ] No
```
=> DTSCCI-1298 update privilege-calendar.json to cater 27th dec 2024

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
Changes for
https://tools.hmcts.net/jira/browse/CIV-15729
https://tools.hmcts.net/jira/browse/CIV-15738
```
[ ] Yes
[ x] No
```
=> CIV-15729 civ 15738 listing tasks

src/main/resources/wa-task-initiation-civil-civil.dmn
remove toggle  "multiOrIntermediateClaim" demo
```
[ ] Yes
[x ] No
```
=> CIV-0000 remove toggle  "multiOrIntermediateClaim" demo

src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-16314
Add permissions for hearing centre team leader
```
[ ] Yes
[x] No
```
=> CIV-16314 - hearing centre team leader permission manage stay

src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
Fix "worktype" - should be "workType"
```
[ ] Yes
[x] No
```
=> CIV-0000 Fix "worktype" - should be "workType"

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16387
Update initiation dmn for relist task
Initiation
```
[ ] Yes
[x] No
```
=> CIV-16387 - initiation change for relist task

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-16559
=> CIV-16559 Cancel Tasks When All Final Orders Issues

src/main/resources/wa-task-completion-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancelAllTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-16543
Added Query Management task configuration.
```
[ ] Yes
[X] No
```
=> CIV-16543 QM Integration

src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16642
Release configuration for Caseworker events R2
```
[ ] Yes
[x] No
```
=> CIV-16642 - Remove feature toggle for CE_B2

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
DTSCCI-1191
amend task name
```
[ ] Yes
[ ] No
```
=> DTSCCI-1191 amend task name

charts/civil-task-configuration/Chart.yaml
=> DTSCCI-1691 bump deprecated java chart

src/main/resources/wa-task-configuration-civil-generalapplication.dmn
=> DTSCCI-0000 - Add work type LegalAdvisorRevisitApplication

src/main/resources/wa-task-configuration-civil-generalapplication.dmn
https://tools.hmcts.net/jira/browse/DTSCCI-1831
```
[ ] Yes
[ ] No
```
=> DTSCCI-1831 - resolve role category issue

src/main/resources/wa-task-cancellation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/CIV-16968
```
[ ] Yes
[ ] No
```
=> CIV-16968 Cosc - HWF cancel WA task

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-20
https://tools.hmcts.net/jira/browse/DTSCCI-253
Claims over 10k now go to judges, all claims <= 10k now go to LAs for SDOs (Fast and Small Track Directions tasks)
```
[ ] Yes
[ ] No
```
=> DTSCCI-020 - And 253 - Update SDO tasks to New Legal Rules

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
=> DTSCCI-000 - Add WA retrigger for Mediation Unsuccessful

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16845
Updated and added rule to create uploadTranslatedDocument WA task.
```
[ ] Yes
[x] No
```
=> CIV-16845 - Update flag to detect language preference for SDO translation

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-17037
Added new role to access profile.
```
[ ] Yes
[x] No
```
=> CIV-17037 - Pre-requisite changes for work allocating to WLU 

build.gradle, src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-civil.dmn, src/main/resources/wa-task-configuration-civil-generalapplication.dmn, src/main/resources/wa-task-permissions-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-16855
changed permission translated document task to wlu-admin
```
[ ] Yes
[x ] No
```
=> CIV-16855  Amend existing translation WA tasks to direct to WLU (Gen Apps)

config/owasp/suppressions.xml, src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16888
Add two tasks, to cover English To Welsh requestTranslation tasks at response stages
```
[ ] Yes
[x] No
```
=> CIV-16888 - cover English to Welsh scenarios

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-17066
```
[ ] Yes
[x] No
```
=> CIV-17066 - Replace NRO LiP Hearing tasks by HMC Hearing tasks

src/main/resources/wa-task-initiation-civil-civil.dmn
https://tools.hmcts.net/jira/browse/DTSCCI-1906
```
[ ] Yes
[ ] No
```
=> DTSCCI-1906 - Update Request for Consideration claim threshold to 10k or greater

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16867
Added rules to create a WA task to Upload Manual determination translated document.
```
[ ] Yes
[x] No
```
=> CIV-16867 - Delay notifications and visibility of Manual Determination document (includes show element)

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16865
Add task for uploading translated settlement agreement
```
[ ] Yes
[x] No
```
=> CIV-16865 Add task for uploading translated settlement agreement

src/main/resources/wa-task-initiation-civil-civil.dmn, src/main/resources/wa-task-permissions-civil-civil.dmn, src/main/resources/wa-task-types-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/CIV-16880
Translation task for court officer order
```
[ ] Yes
[x] No
```
=> CIV-16880 Translation task for court officer order

Jenkinsfile_CNP, Jenkinsfile_nightly, bin/run-civil-ccd-task-tests.sh, bin/run-nightly-civil-ccd-task-tests.sh, build.gradle
=> DTSCCI-2255 Implement Run Failed Tests on Nightly and PR

Jenkinsfile_CNP
=> DTSCCI-2255 Add 'aat' Env Variable to Master

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16859
[delay notification and visibility of the docs](https://github.com/hmcts/civil-wa-task-configuration/pull/909#top)
```
[ ] Yes
[x ] No
```
=> CIV-16859 delay notification and visibility of the docs

charts/civil-task-configuration/Chart.yaml
=> DTSCCI-2265 use oci endpoint

config/owasp/suppressions.xml
=> CIV-0000 supress CVE-2024-22259

src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-17132
```
[ ] Yes
[ ] No
```
=> CIV-7132 pause in defendant response journey for lip vs lr

.github/workflows/ado_artifacts_build.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> DTSCCI-2086 swtich from jitpack config

build.gradle
=> CIV-0000 Fix cve issues

Jenkinsfile_CNP, Jenkinsfile_nightly, bin/run-civil-ccd-task-tests.sh, build.gradle
=> DTSCCI-2334 Implement Run Failed Tests as Default Behaviour to Master and PR

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16899
https://tools.hmcts.net/jira/browse/CIV-16901
translation general order 
```
[ ] Yes
[x] No
```
=> CIV-16899 translation general order

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16897
Update rule for dismissal order translation
```
[ ] Yes
[x] No
```
=> CIV-16897 Update rule for dismissal order translation

config/owasp/suppressions.xml
=> DTSCCI-000 Add CVE Suppressions

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/CIV-16906
Refactored Hearing Order - Upload Translated document rule.
```
[ ] Yes
[x] No
```
=> CIV-16906 - Translation of GA hearing order document - pause and unpause

src/main/resources/wa-task-initiation-civil-generalapplication.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-16907
CIV-16907 Pause and Unpause of GA during translation of hearing notice (GA) 
```
[ ] Yes
[ ] No
```
=> CIV-16907 Pause and Unpause of GA during translation of hearing notice (GA)

src/main/resources/wa-task-cancellation-civil-civil.dmn, src/main/resources/wa-task-initiation-civil-civil.dmn, src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/CIV-17571 
Add warning for multiOrIntermediateClaim tasks.
```
[ ] Yes
[ x ] No
```
=> CIV-17571 add warning text minti

charts/civil-task-configuration/values.preview.template.yaml
DTSCCI-938
Point to hard coded ccd image
```
[ ] Yes
[ ] No
```
=> Point to hard coded ccd image
